; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform = espressif32@6.9.0
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
board_build.partitions = min_spiffs.csv
lib_deps = 
	wollewald/INA226_WE@^1.3.0
	paulstoffregen/OneWire@^2.3.8
	milesburton/DallasTemperature@^4.0.6
	adafruit/RTClib@^2.1.4
	bblanchon/ArduinoJson @ ^6.21.3
	crankyoldgit/IRremoteESP8266
	Blynk
build_flags = 
    -D BLYNK_FIRMWARE_VERSION=\"0.2.6\"
build_type = debug
monitor_filters = esp32_exception_decoder
test_framework = unity
test_build_src = yes

[env:ir_transceiver]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
build_src_filter = -<*> +<../utils/IrTransceiver.cpp> 
lib_deps = 
    crankyoldgit/IRremoteESP8266 @ ^2.8.6
