name: Build and Release Firmware

on:
  push:
    tags:
      - 'v*' # สคริปต์จะทำงานเมื่อคุณสร้าง Tag เช่น v1.0.0, v1.1.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache PlatformIO & Build Files
        uses: actions/cache@v4
        with:
          # Keep both PlatformIO global cache and project-specific .pio folder to speed up subsequent builds
          path: |
            ~/.platformio
            .pio
          key: ${{ runner.os }}-pio-${{ hashFiles('**/platformio.ini') }}
          restore-keys: |
            ${{ runner.os }}-pio-

      - name: Install PlatformIO
        run: pip install -U platformio
      
      - name: Create secret.h
        run: |
          cat <<EOF > include/secret.h
          #pragma once
          #define SECRET_SSID_HOME "${{ secrets.WIFI_SSID_HOME }}"
          #define SECRET_PASS_HOME "${{ secrets.WIFI_PASS_HOME }}"
          #define SECRET_SSID_BOSS "${{ secrets.WIFI_SSID_BOSS }}"
          #define SECRET_PASS_BOSS "${{ secrets.WIFI_PASS_BOSS }}"
          #define SECRET_OTA_HOSTNAME "${{ secrets.OTA_HOSTNAME }}"
          #define SECRET_OTA_PASS "${{ secrets.OTA_PASS }}"
          #define SECRET_OTA_UPDATE_URL "${{ secrets.OTA_UPDATE_URL }}"
          EOF

      - name: Build Firmware
        env:
          VERSION: ${{ github.ref_name }}
        run: |
          export PLATFORMIO_BUILD_FLAGS="-DFIRMWARE_VERSION='\"$VERSION\"'"
          pio run -e esp32doit-devkit-v1

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: .pio/build/esp32doit-devkit-v1/firmware.bin
          name: Release ${{ github.ref_name }}
          body: "Auto-generated release for version ${{ github.ref_name }}"
          draft: false
          prerelease: false